#!/usr/bin/env python3.7
import os.path
import sys
import re
import getopt
from glob import glob
from pprint import pprint
from vella.workinstruction import Workinstruction, WiShell

Location = "/home/vella/work_instructions"

class DirNotExists(Exception):
    pass

def usage(self):
    print("""
Usage: %s <option> [ <value> ]
Options:
    -h|--help               print this helpfull message
    -l|--location <dir>     point to where work instructions live
""" % self)

def main(argv):
    try:
        opts, args = getopt.getopt(argv[1:], "hl:", ["help", "location="])
    except getopt.GetoptError as e:
        print("ERROR: %s" % str(e))
        usage(argv[0])
        sys.exit(127)

    location = Location # set default
    for opt, arg in opts:
        if opt == "-h" or opt == "--help":
            usage(argv[0])
            sys.exit(0)

        if opt == "-l" or opt == "--location":
            location = arg

    if not os.path.isdir(location):
        raise DirNotExists(location)

    wis = {}
    for name in glob("%s/*" % location):
        if not os.path.isdir(name):
            continue

        i = re.search(r'/(.*)$', name)
        if not i:
            print("Could not match instruction name in '%s', skipping" % name)
            continue

        wi = Workinstruction(i.group(1), name)
        wis[wi.getName()] = wi

    wshell = WiShell(wis, "vella-work-instruct>")
    wshell.run()

if __name__ == "__main__":
    main(sys.argv)
    sys.exit(0)
